launch:
  handedness: left
  arm_slot: 38.1 degree
  position:
    height: 6 ft
    release_pos:
    - 2.45 ft
    - 54.35 ft
    - 5.21 ft
  speed: 97.1 mph
  spin: 2533.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: -19.9000 degree
  velocity:
    vector:
    - -8.589491164718055 ft/s
    - -141.21859505018912 ft/s
    - -1.3371693234953916 ft/s
    statcast: true
training:
  ax: 8.729750 ft/s**2
  ay: 32.143261 ft/s**2
  az: -13.726281 ft/s**2
