launch:
  handedness: left
  arm_slot: 33.6 degree
  position:
    height: 6 ft
    release_pos:
    - 2.57 ft
    - 54.36 ft
    - 5.02 ft
  speed: 89.7 mph
  spin: 2637.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: -130.4000 degree
  velocity:
    vector:
    - -6.436125826871996 ft/s
    - -130.57872912111685 ft/s
    - -2.8335386904886777 ft/s
    statcast: true
training:
  ax: -4.673853 ft/s**2
  ay: 25.753074 ft/s**2
  az: -30.304070 ft/s**2
