launch:
  handedness: left
  arm_slot: 32.2 degree
  position:
    height: 6 ft
    release_pos:
    - 2.57 ft
    - 54.32 ft
    - 5.02 ft
  speed: 96.7 mph
  spin: 2611.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: -12.8000 degree
  velocity:
    vector:
    - -9.945687003427976 ft/s
    - -140.48992835831913 ft/s
    - -4.718294634438112 ft/s
    statcast: true
training:
  ax: 10.780892 ft/s**2
  ay: 31.549178 ft/s**2
  az: -11.455006 ft/s**2
