launch:
  handedness: left
  arm_slot: 30.9 degree
  position:
    height: 6 ft
    release_pos:
    - 2.75 ft
    - 54.48 ft
    - 4.97 ft
  speed: 97.0 mph
  spin: 2486.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: -23.1000 degree
  velocity:
    vector:
    - -5.0340035521440765 ft/s
    - -141.20671558066607 ft/s
    - -3.176848192261845 ft/s
    statcast: true
training:
  ax: 10.355227 ft/s**2
  ay: 31.337800 ft/s**2
  az: -14.378512 ft/s**2
