launch:
  handedness: left
  arm_slot: 34.7 degree
  position:
    height: 6 ft
    release_pos:
    - 2.68 ft
    - 54.38 ft
    - 5.18 ft
  speed: 89.9 mph
  spin: 2637.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: -83.3000 degree
  velocity:
    vector:
    - -10.188640177421496 ft/s
    - -130.5775201305516 ft/s
    - -3.375930538776299 ft/s
    statcast: true
training:
  ax: -3.070114 ft/s**2
  ay: 25.429790 ft/s**2
  az: -26.192940 ft/s**2
