launch:
  handedness: left
  arm_slot: 32.3 degree
  position:
    height: 6 ft
    release_pos:
    - 2.55 ft
    - 54.28 ft
    - 5.09 ft
  speed: 90.1 mph
  spin: 2757.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: -113.7000 degree
  velocity:
    vector:
    - -8.520868710792119 ft/s
    - -131.00529482184004 ft/s
    - -5.133305775695746 ft/s
