launch:
  handedness: right
  arm_slot: 26.4 degree
  position:
    height: 6 ft 2 in
    release_pos:
    - -2.12 ft
    - 53.24 ft
    - 5.43 ft
  speed: 91.1 mph
  spin: 2205.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: 19.6000 degree
  velocity:
    vector:
    - 7.963112063174195 ft/s
    - -132.26734036528543 ft/s
    - -1.949820453264563 ft/s
    statcast: true
training:
  ax: -12.198839 ft/s**2
  ay: 33.030378 ft/s**2
  az: -13.982743 ft/s**2
