launch:
  handedness: right
  arm_slot: 16.0 degree
  position:
    height: 6 ft 2 in
    release_pos:
    - -2.35 ft
    - 53.51 ft
    - 5.26 ft
  speed: 83.4 mph
  spin: 2556.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: -17.0000 degree
  velocity:
    vector:
    - 9.068371965088344 ft/s
    - -120.9433176556314 ft/s
    - 0.232972405215607 ft/s
