launch:
  handedness: right
  arm_slot: 15.2 degree
  position:
    height: 6 ft 2 in
    release_pos:
    - -2.28 ft
    - 53.64 ft
    - 5.22 ft
  speed: 82.6 mph
  spin: 2564.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: -16.2000 degree
  velocity:
    vector:
    - 10.012650056681156 ft/s
    - -119.73469101891013 ft/s
    - -2.2131036595417335 ft/s
    statcast: true
training:
  ax: -19.171522 ft/s**2
  ay: 28.792750 ft/s**2
  az: -34.194707 ft/s**2
