launch:
  handedness: right
  arm_slot: 24.4 degree
  position:
    height: 6 ft 2 in
    release_pos:
    - -2.06 ft
    - 53.26 ft
    - 5.4 ft
  speed: 93.1 mph
  spin: 2354.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: 24.6000 degree
  velocity:
    vector:
    - 10.604043458789835 ft/s
    - -135.05364618283517 ft/s
    - -1.591765030029054 ft/s
