launch:
  handedness: right
  arm_slot: 14.7 degree
  position:
    height: 6 ft 2 in
    release_pos:
    - -2.36 ft
    - 53.45 ft
    - 5.2 ft
  speed: 84.4 mph
  spin: 2613.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: -19.7000 degree
  velocity:
    vector:
    - 9.300375316695686 ft/s
    - -122.41371526908456 ft/s
    - -2.348256680172998 ft/s
