launch:
  handedness: right
  arm_slot: 39 degree
  position:
    height: 6.0 ft
  speed: 97.3 mph
  spin: 2533.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: 10.00 degree
  velocity:
    target: ["0.05 m", "0 m", "1.0 m"]
training:
  ax: 8.729750 ft/s**2
  ay: 32.143261 ft/s**2
  az: -13.726281 ft/s**2
