launch:
  handedness: right
  arm_slot: 40 degree
  position:
    height: 6.0 ft
  speed: 90.1 mph
  spin: 2533.0 rpm
  spin_axis:
  - 1
  - 0
  - 0
  clock_angle: 7.00 degree
  velocity:
    target: ["-0.5 m", "0 m", "2.1 m"]
training:
  ax: 8.729750 ft/s**2
  ay: 32.143261 ft/s**2
  az: -13.726281 ft/s**2
