launch:
  handedness: right
  arm_slot: 38 degree
  position:
    height: 6 ft
  speed: 96.6 mph
  spin: 2100.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: -7.2000 degree
  velocity:
    target: ["0.07 m", "0 m", "1.05 m"]
training:
  ax: -21.025890 ft/s**2
  ay: 32.578702 ft/s**2
  az: -28.119031 ft/s**2
  plate_x: -0.331089 ft
  plate_z: 2.143931 ft
