launch:
  handedness: right
  arm_slot: 38 degree
  position:
    height: 6.0 ft
  speed: 94.1 mph
  spin: 2433.0 rpm
  spin_axis:
  - 0
  - 0
  - 1
  clock_angle: 0.00 degree
  velocity:
    target: ["-0.2 m", "0 m", "1 m"]
training:
  ax: 8.729750 ft/s**2
  ay: 32.143261 ft/s**2
  az: -13.726281 ft/s**2
